# Generated by Django 3.1.4 on 2020-12-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('P', 'Programming'), ('T', 'Travel'), ('E', 'Education'), ('O', 'Others')], default='P', max_length=1),
        ),
    ]
