# Generated by Django 3.1.4 on 2020-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('P', 'Programming'), ('T', 'Travel'), ('E', 'Education'), ('O', 'Others')], max_length=1),
        ),
    ]
